### ISSUE TITLE
[tracker] Clean up as much of the test warnings as possible

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons#10413]
There's a few things to complete this:

* [x] Fix sinon deprecation warnings mozilla/addons-frontend#2479
* [ ] Fix warnings about incorrect props
* [x] Fix React deprecation warnings re: proptypes by using the split out package mozilla/addons-frontend#2475
* [x] Move to react-router 4 (since I think some of the deprecations come from there).

There's probably others too.
