### ISSUE TITLE
[tracker] Collections feature

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons#10589]
**The collections feature is being tracked in [this project](https://github.com/mozilla/addons-frontend/projects/3?fullscreen=true)**

Docs / specs:

- [Collections features that we are implementing](https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.z5wk3ws26iay)
- [Overview of simplified Collections](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit#)

See the following links for the separate issues.

**2017 Q3**

- [x] ~~Collection View mozilla/addons-frontend#3140 (MVP)~~
- [x] ~~Link to edit your collection while signed in~~ https://github.com/mozilla/addons-frontend/issues/3766

**2017 Q4**
- *landed platform work needed for 2018 Q1 features*

**2018 Q1**

- [x] ~~Add an add-on to an existing collection~~ mozilla/addons#10575
- [x] ~~Edit collection name, description, URL~~ https://github.com/mozilla/addons-frontend/issues/4002
- [ ] Edit the add-ons in a collection https://github.com/mozilla/addons-frontend/issues/4004
- [ ] Create a new collection https://github.com/mozilla/addons-frontend/issues/4003
- [ ] List my collections and edit / delete / add mozilla/addons-frontend#3142 
- [ ] Add an add-on to a new collection https://github.com/mozilla/addons-frontend/issues/3993

**Future?**

- [ ] Delete a collection https://github.com/mozilla/addons-frontend/issues/4195
- [ ] Allow contributors to maintain a collection https://github.com/mozilla/addons-frontend/issues/4000
- [ ] Show Collection comments https://github.com/mozilla/addons-frontend/issues/3890
- [ ] Sort add-ons in a collection https://github.com/mozilla/addons-frontend/issues/3991
- [ ] Install an add-on from a collection https://github.com/mozilla/addons-frontend/issues/3992
- [ ] On detail page: this add-on is featured in `<Collection>` https://github.com/mozilla/addons-frontend/issues/3994
