### ISSUE TITLE
upgrade api from v3 to v4

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons#12019]
upgrade api from v3 to v4

---

- [x] 2018-05-18: renamed /reviews/ endpoint to /ratings/ https://github.com/mozilla/addons/issues/4984
- [x] 2018-05-25: renamed rating.rating property to rating.score https://github.com/mozilla/addons-server/pull/8332
- [x] 2018-06-05: dropped rating.title property https://github.com/mozilla/addons/issues/5466
- [x] 2018-07-12: added type property to autocomplete API. This change was also backported to the v3 API. https://github.com/mozilla/addons/issues/5759
- ~~2018-07-19: localised field values are always returned as objects, even if only a single language is requested. Setting a localised value with a string is removed too - it must always be an object of one or more translations. https://github.com/mozilla/addons/issues/5757~~
- [x] 2018-07-18: added previews property to discovery API addons object. This change was also backported to the v3 API. https://github.com/mozilla/addons/issues/5783
- [x] 2018-07-20: dropped downloads property from the collection add-ons results. https://github.com/mozilla/addons/issues/5818
- [x] 2018-08-16: added is_developer_reply property to ratings. This changed was also backported to the v3 API. https://github.com/mozilla/addons/issues/5840
- [x] 2018-09-13: added name and icon_url properties to the addon object in ratings. This changed was also backported to the v3 API. https://github.com/mozilla/addons/issues/5953
- [x] 2018-09-27: backed out “localised field values are always returned as objects” change from 2018-07-19 from v4 API. This is intended to be temporary change while addons-frontend upgrades. On addons-dev and addons stage enviroments the previous behavior is available as api/v4dev. The v4dev api is not available on AMO production server. https://github.com/mozilla/addons/issues/5999
