### ISSUE TITLE
Add <meta name="description”> for all other pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons#12132]
Following on from https://github.com/mozilla/addons-frontend/issues/5766 we should also add descriptions to all other relevant pages represented by the new frontend.

See also https://docs.google.com/document/d/1W9LOw7wgbpY6Mw5Zd4V71hJ0YahY4DTNl23MHVpG0_E/edit?ts=5b5b40e5#heading=h.aqjhycqt8ulj

## Pages

⚠️ all of the page below are available for Firefox and Android (Firefox for Android):

- [x] Homepage: https://addons.mozilla.org/en-US/firefox/
- [x] Landing Extensions: https://addons.mozilla.org/en-US/firefox/extensions/
- [x] Landing Themes: https://addons.mozilla.org/en-US/firefox/themes/
- [x] Search tools: https://addons.mozilla.org/en-US/firefox/search-tools/
- [x] Reviews for an add-on: https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/reviews/ --> https://github.com/mozilla/addons-frontend/pull/6712
- [x] user profile of a developer or artist or both: https://addons.mozilla.org/en-US/firefox/user/Testfahrer/
- Themes / category pages (https://addons.mozilla.org/en-US/firefox/themes/):
  - [x] Abstract
  - [x] Causes
  - [x] Fashion
  - [x] Film and TV
  - [x] Firefox
  - [x] Foxkeh
  - [x] Holiday
  - [x] Music
  - [x] Nature
  - [x] Other
  - [x] Scenery
  - [x] Seasonal
  - [x] Solid
  - [x] Sports
  - [x] Websites
- [x] About page: https://addons.mozilla.org/en-US/about
- [x] Review guide: https://addons.mozilla.org/en-US/review_guide
- [x] Collection pages (we can probably rely on the description of the collection, but there might be something to add before): https://addons.mozilla.org/en-US/firefox/collections/mozilla/ad-blockers/

Firefox-only pages:

- [x] Dictionaries and Lang Packs: https://addons.mozilla.org/en-US/firefox/language-tools/
- Extensions / category pages (https://addons.mozilla.org/en-US/firefox/extensions/):
  - [x] Alerts & Updates
  - [x] Appearance
  - [x] Bookmarks
  - [x] Download Management
  - [x] Feeds, News & Blogging
  - [x] Games & Entertainment
  - [x] Language Support
  - [x] Other
  - [x] Photos, Music & Videos
  - [x] Privacy & Security
  - [x] Search Tools
  - [x] Shopping
  - [x] Social & Communication
  - [x] Tabs
  - [x] Web Development

Android-only pages:

- Extensions / category pages (https://addons.mozilla.org/en-US/android/extensions/):
  - [x] Device Features & Location
  - [x] Experimental
  - [x] Feeds, News, & Blogging
  - [x] Other
  - [x] Performance
  - [x] Photos & Media
  - [x] Security & Privacy
  - [x] Shopping
  - [x] Social Networking
  - [x] Sports & Games
  - [x] User Interface
