### ISSUE TITLE
Switch to Node 16 across all our projects

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1437]
We're using Node 14 across our projects, but it's reaching EOL soon (2023-04-30). This is a tracking issue for switching all our projects to Node 16 in dev/stage/prod.

Every repos except addons-code-manager should already be compatible and have been running tests against Node 16 for a while.

- [x] addons-frontend https://github.com/mozilla/addons-frontend/issues/11865
- [x] addons-server (linter, assets build) https://github.com/mozilla/addons-server/issues/19750
- [x] addons-customs-scanner https://github.com/mozilla-services/addons-customs-scanner/issues/1464
- [x] addons-code-manager https://github.com/mozilla/addons-code-manager/issues/2176
  - [x] Pre-requisite: https://github.com/mozilla/addons-code-manager/issues/2014
- [x] addons-blog (it's just used for building) https://github.com/mozilla/addons-blog/issues/400
- [x] extension-workshop (should already be the case, it's just used for building)
- [x] Once we've migrated all environments, we should also stop testing with Node 14, using Node 16 as the base version instead, and start testing with Node 18 as the "next" version.

**Comment by diox** [comment]
The last one to be updated will be addons-frontend next week. All issues are now done, closing this.
