### ISSUE TITLE
[Task]: Prevent URLs from being added to the summary of add-ons

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14953]
### Description

We are seeing a large number of themes being used for URL spam.  Many of these add a URL to the summary of an add-on with anchor text.

This task is to prevent URLs from being allowed in the summary of an add-on.

![image](https://github.com/user-attachments/assets/1103574a-826b-4811-a1b2-a07ed0f713be)

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Add-ons do not allow URLs to be added to the summary
- [ ] A user who adds a URL to a summary and submits the listing is denied and informed that URLs are not allowed in the summary.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-973)

**Comment by diox** [comment]
For the moment we have decided to leave the existing summaries intact.

**Comment by diox** [comment]
Summary is currently defined with:
```
summary = LinkifiedField(max_length=250)
```

We'll likely want `NoURLsField` instead.

**Comment by ioanarusiczki** [comment]
I tried to edit the summary using urls from dev hub 

![urls not allowed](https://github.com/user-attachments/assets/e18dc27c-3cf5-4a31-8bcf-d60d39b8b7ee)

When creating or editing summary details using the endpoints with multiple languages -> it's a 400 "URLs are not allowed"

While testing this with endpoints I've noticed that admins can edit eula/privacy policy yet can't edit addon details when they're not owners of those extensions, so I filed https://github.com/mozilla/addons/issues/14966.
