### ISSUE TITLE
[Task]: Do not expose information about an add-on being Notable or Strategic in API

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#14987]
### Description

In the public API, a Notable or Strategic add-on should not show its state in `promoted.categories`. Accordingly, the add-ons search should not return any `Notable`,  `Strategic` or `Partner` add-ons, even if queried for that.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Do not display if an add-on is `Notable` in the public API
- [ ] Do not display if an add-on is `Strategic` in the public API
- [ ] Do not display if an add-on is `Partner` in the public API
- [ ] Do not allow the querying for Notable, Strategic, or Partner add-ons via AMO Search
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1012)

**Comment by eviljeff** [comment]
@abyrne-moz to confirm, only `Notable` is excluded; all other promoted classes (strategic, etc) are to be exposed as now?

**Comment by abyrne-moz** [comment]
I spoke to Andreas about this, and we should exclude Strategic as well please.  I'll update the description to reflect this.

**Comment by wagnerand** [comment]
What about _sponsored_ and _verified_?

**Comment by abyrne-moz** [comment]
I thought these categories were no longer used and didn't apply to any current add-ons.  If this is correct, is there any reason to do this?  Or did I misunderstand.

**Comment by eviljeff** [comment]
Note, sponsored and verified were specifically _meant_ to be exposed, and the presence of those promoted groups is used by frontend too, including as part of the "badged" pseudo-group.  If the ask is to completely remove support for verified and sponsored please file as a separate issue, as it's a larger scope.

**Comment by wagnerand** [comment]
> I thought these categories were no longer used and didn't apply to any current add-ons. If this is correct, is there any reason to do this? Or did I misunderstand.

As we know with strategic, the fact they are not used can change at any point in time, at which point this question will become relevant for them immediately. At that point, we would run into a timing issue. as the engineering cycle takes some time. Also, it's easier to touch this code once, rather than multiple times to address individual instances.

**Comment by wagnerand** [comment]
> Note, sponsored and verified were specifically _meant_ to be exposed, and the presence of those promoted groups is used by frontend too, including as part of the "badged" pseudo-group. If the ask is to completely remove support for verified and sponsored please file as a separate issue, as it's a larger scope.

The ask is not to remove, the ask is to be aware of the categories and make a conscious decision about them, like I did in https://github.com/mozilla/addons/issues/14980. That issue also specifies that `sponsored` and `verified` keep being exposed.

**Comment by eviljeff** [comment]
> > Note, sponsored and verified were specifically _meant_ to be exposed, and the presence of those promoted groups is used by frontend too, including as part of the "badged" pseudo-group. If the ask is to completely remove support for verified and sponsored please file as a separate issue, as it's a larger scope.
> 
> The ask is not to remove, the ask is to be aware of the categories and make a conscious decision about them, like I did in #14980. That issue also specifies that `sponsored` and `verified` keep being exposed.

#14980 is closed and not a dependency of this issue.  If you think there is something from that issue which is relevant here - like needing to enumerate every promoted group and stating if that group should be exposed or not - can you (or Alan) update the description?

**Comment by chrstinalin** [comment]
@abyrne-moz Would partner add-ons (once added as part of #14986) be included in this as well?

**Comment by ioanarusiczki** [comment]
@chrstinalin 

For notable, strategic or partner I see `"promoted": []` in the api.

Examples: 

strategic https://addons-dev.allizom.org/api/v5/addons/addon/637450/
notable  https://addons-dev.allizom.org/api/v5/addons/addon/637454/ 
partner  https://addons-dev.allizom.org/api/v5/addons/addon/637455/ 

[Multiple promoted add-ons](https://addons-dev.allizom.org/api/v5/addons/addon/637456/ ) won't expose notable, strategic or partner in api, they expose them in dev hub but that has been filed https://github.com/mozilla/addons/issues/15548

There is a change for Recommended, By Firefox and Spotlight compared to the -stage api response. 

For example, right after adding the addon to a promotion on dev it's  `"promoted": []` until confirm approval or approval of a new version. Meanwhile on -stage this would be already exposed as "line".  Also looking in dev hub on -dev the status "Approved and By Firefox"  is not exposed yet, on -stage it's already visible.  -> but this should be ok 

dev  https://addons-dev.allizom.org/api/v5/addons/addon/637453/ 
stage  https://addons.allizom.org/api/v5/addons/addon/2247538/
