### ISSUE TITLE
[Task]: Remove obsolete validator caching feature

### ISSUE THREAD

**Issue by diox** [mozilla/addons#14995]
### Description

Our validation task logic caches the task id to avoid repeating the validation tasks for a given file more than once.

This was added back in the day because reviewers and developers were able to trigger the validation task (synchronous!) in case it had failed to run on existing files: https://bugzilla.mozilla.org/show_bug.cgi?id=1191603. 

Eventually that functionality was removed in https://github.com/mozilla/addons/issues/7012 as it wasn't really useful - we had started enforcing validation for all uploads long ago anyway.

This makes the caching obsolete. Worse, it was silently broken for a while, when we were using post-request-task, as the `task_id` returned could be wrong.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Validation after uploading a new add-on works normally with caching removed
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1021)

**Comment by ioanarusiczki** [comment]
I didn't see anything unusual while making uploads for https://github.com/mozilla/addons/issues/1968
Also I tried dev versus stage for a few addons to check  validation results and they looked identical. 

Let me know if there's anything else.
