### ISSUE TITLE
[Task]:  DevHub Pastebin Re-implementation

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#14998]
### Description

Reviewers need a way to communicate build logs with developers and rely on Pastebin to do so. With its decommission, this task is a part of the [re-implementation](https://docs.google.com/document/d/1iy6OV8il2GQ_p5286I8Y81d-paPk5v93Gp-RMLoZBtc/edit?pli=1) of pastebin.mozilla.org on the DevHub side.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] Modify the `reviewnotes` endpoint to expose the fact that there exists an attachment through the activity log API via an attachment_url.
- [x] Surface said attachments in the review history of the add-on version.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1024)
