### ISSUE TITLE
[Task]:  Reviewer Tools Pastebin Re-implementation

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#14997]
### Description

Reviewers need a way to communicate build logs with developers and rely on Pastebin to do so. With its decommission, this task is a part of the [re-implementation](https://docs.google.com/document/d/1iy6OV8il2GQ_p5286I8Y81d-paPk5v93Gp-RMLoZBtc/edit?pli=1) of pastebin.mozilla.org on the Reviewer Tools side.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] New text/file input field in the “reviewer reply” form to allow a reviewer to upload or paste build logs.
- [x] Attach the build logs as a new model linking to the activity log though a OneToOneField
- [x] Surface the logs in the reviewer tools for reviewers.
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1023)

**Comment by diox** [comment]
Note: for storage, please use `id_to_path(<id>, breadth=2)` in the `upload_to` parameter of the `FileField`, and a dedicated folder under `shared_storage` (your storage parameter should be set to `SafeStorage(root_setting='MEDIA_ROOT')`)

Then we'll need to communicate that storage path to SRE to adjust the nginx configuration in dev/stage/prod.

**Comment by ioanarusiczki** [comment]
I don't see this on -dev yet but maybe because of what @diox said above.

**Comment by diox** [comment]
Work is technically done but won't be enabled yet, it's behind a waffle switch, so moving to the next milestone.

**Comment by diox** [comment]
@ioanarusiczki : Waffle switch to enable this feature is `enable-activity-log-attachments`. It should work on dev now that Wei has done https://mozilla-hub.atlassian.net/browse/SVCSE-2218

**Comment by ioanarusiczki** [comment]
I started looking over, I've seen there is a [switch](https://github.com/mozilla/addons-server/pull/22640). So far:

- all reviewer actions have this attachment possibility including unreject or flag for human review
- the download attachment throw a 404 when clicked. I tried with https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/633005. 
- I could upload small zip files, when I try something a bit larger (actually I used zipped extensions of 2 MB or Ublock origin , which is 3MB+), I get a 413 error

![413](https://github.com/user-attachments/assets/5142c842-b115-4f4a-ab2c-bb810caedf8b)

- the Paste from Clipboard worked from win10, the download throws an error (same as for the zip files attached)
- I did not try all the possible reviewer actions to check the emails, but that would be https://github.com/mozilla/addons/issues/15018. So far, I did notice that reviewer's reply email has this but I did not see a reference to it for approve or reject (will re-check anyway).

**Comment by chrstinalin** [comment]
For sanity, double-checked master branch locally -- 
- Download attachment works as expected on both reviewer tools and DevHub without a 404.
- Couldn't replicate the 413 error due to the local 502 error (#15029). However, with the workaround for the latter, files up to 200mb are uploaded as expected.
![image](https://github.com/user-attachments/assets/e5cb2e22-9fab-4b02-ad0c-9927e03e6ec4)
- Only `from_reviewer.txt` email template was modified. I just checked and it looks like approval/rejections are in a separate email template. Reopened #15018

**Comment by diox** [comment]
@chrstinalin: The 404 is the addons-frontend one, so it seems we're missing the nginx config to route these kind of URLs to addons-server. Did we file the ticket for SRE to do that ?

**Comment by diox** [comment]
There are 2:
- We need the storage path (on the filesystem) for the attachments to be set as [`internal` in nginx](https://nginx.org/en/docs/http/ngx_http_core_module.html#internal), allowing `HttpResponseXSendFile` (which does a `X-Accel-Redirect`) to work. That's https://mozilla-hub.atlassian.net/browse/SVCSE-2218
- We need the URL for the attachements to be served by addons-server, as by default nginx will route things to addons-frontend. That's missing. That was discussed at some point but maybe not written so we forgot to file that issue, my bad.

Could you file it? Example from a previous time we needed to do that some time ago: https://mozilla-hub.atlassian.net/browse/SVCSE-1563

**Comment by ioanarusiczki** [comment]
I'm going to mark this verified, I enabled the switch on stage and for any reviewer action I could:
- attach a zip or txt file. 
- use paste from clipboard worked and it will attach a txt file, Windows has a build-in Clipboard History which I found really nice to use, macOS needs an app to do something similar so I found a solution and I could drag and drop text or emojis in the Attachment box.
- could not attach a larger zip on stage either but there is an issue for it https://github.com/mozilla/addons/issues/14999 
- I added a comment on https://github.com/mozilla/addons/issues/15018 with things noticed while testing with emails today.
