### ISSUE TITLE
[Task]: Implement soft-blocking backend

### ISSUE THREAD

**Issue by diox** [mozilla/addons#15012]
### Description

Part of https://docs.google.com/document/d/1RgY1N5MCNQAiKM3EK0bgvw7CZ8TolR81dF2QCNzTM2s/edit

We want to add the ability for versions to be soft-blocked. 

Minimal changes to the admin should be included to make it possible to test this.

In follow-up tickets we'll add more admin functionality and generate a separate set of bloomfilter and stashes for soft-blocked versions - for now, this is about making it possible to add a soft-block internally without breaking anything.

Note that while in practice this is unlikely to come up very often, for a given `Block` we might end up with versions that are hard-blocked and versions that are soft-blocked : we are going to add the information of whether something is soft or hard-blocked on the `BlockVersion` itself.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] `BlockVersion` has the concept of a hard vs a soft block
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1047)

**Comment by diox** [comment]
> Minimal changes to the admin should be included to make it possible to test this.

Creating/editing has been left for later, for https://github.com/mozilla/addons/issues/15013, so to test this requires manually altering the blockversion in a shell. Still, you can test that all blocks are created as hard by default (the admin detail for a block now shows if each version in the block was soft or hard blocked)

**Comment by ioanarusiczki** [comment]
The only place I see this is when I go to [Edit block](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26443/change/) 

![hardblock](https://github.com/user-attachments/assets/0e0b5d46-2ddd-485a-85d5-ab2aae1481b1)

I hope that's the expected for now.
