### ISSUE TITLE
[Task]: Pastebin - Include link to any attachment in any action

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15018]
### Description

When an attachment is included in an action, the email to the developer should include a link to view the attachment.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] The email includes a link to view attachments (if any are created).
```

### Checks

- [X] If the issue is ready to work on, I have removed the "needs:info" label.
- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1057)

**Comment by wagnerand** [comment]
This should be "in any action", not just reviewer replies.

**Comment by ioanarusiczki** [comment]
I did not finish testing this but I should update with some things noticed so far:

- downloading attachments from dev hub throws a 404 with a developer account (but it's working with admin). Downloads from rev tools pages are working now (I only checked with an admin account). Mmm, don't know what is going on yet.

- I checked emails for approve, reject, delay reject, force disable, force enable actions. Everywhere I see the new line attached, for example "An attachment was provided. To respond or view the file, visit https://addons-dev.allizom.org/developers/addon/blue-overdose-theme3/versions." Maybe to be more specific since approve or reject won't display a count next to review history - it should be "... visit Review History from https://addons-dev.allizom.org/developers/addon/blue-overdose-theme3/versions"

- force disable with file attachments won't be displayed in dev hub for the developer. An [example](https://addons-dev.allizom.org/en-US/developers/addon/reported-for-add-on-policies/versions). 

- force enable with file attachments will be available in review history for the developer but it won't be anywhere visible for reviewers. [Example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/633116) 

I still need to look over some reviewer actions with abuse reports attached (or appeals) too. And I'm going to file tomorrow separate followups if needed.

**Comment by chrstinalin** [comment]
> downloading attachments from dev hub throws a 404 with a developer account (but it's working with admin). Downloads from rev tools pages are working now (I only checked with an admin account). Mmm, don't know what is going on yet.

Filed #15062

> force disable with file attachments won't be displayed in dev hub for the developer. An [example](https://addons-dev.allizom.org/en-US/developers/addon/reported-for-add-on-policies/versions).
> force enable with file attachments will be available in review history for the developer but it won't be anywhere visible for reviewers. [Example](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/633116)

Looks like force disable/enable are not surfaced in review history, presumably by design? Would it be better to disable attachments for these actions to avoid this confusion? @diox

**Comment by diox** [comment]
Force disable/enable apply on the whole add-on, which is why they are not easy to see for developers. I'll leave to @wagnerand whether or not we care not to allow adding attachments to those actions.

**Comment by wagnerand** [comment]
Ideally, we would allow attachments for force-disabling and -enabling, just to have that opportunity. However, I can't think of a scenario at the moment where we would need that and given that it would create visibility issues for developers, it's better to not allow it for the moment. When we do need in the future, we would make sure it's properly accessible to developers as well.

**Comment by ioanarusiczki** [comment]
I've some more things from today's stage testing:

-  I don't know if that's expected: developers can see attachments for clear pending rejections or unrejects

![pending rejection cleared](https://github.com/user-attachments/assets/58f18e90-ec5f-420e-98e7-77d11d0faaf0)
![unreject](https://github.com/user-attachments/assets/a6abc73b-2c42-4123-9096-cb8b1e6e762f)

- going over abuse reports/appeals, if  zip or txt files can be attached to any reviewer action, this is applied for approve/ignore actions from Resolve Reports. These would be attachments to be viewed only by reviewers (they don't go as links to any email, as it would be for Comment).

- for an author's appeal resolved with reject or approve: checking the email sent to developers, the new line is present and files are attached in dev hub. (this is expected)

- an author appeal could be resolved in rev tools with Deny action. The email sent has "An attachment was provided. To respond or view the file, visit https://addons.allizom.org/developers/addon/test_for_email_checks/versions." ( applied on version 4.0 in this case) but this is not an action visible for a developer in dev hub. 

- I can download the attachments from rev tools as an admin, admin reviewer, addon reviewer but I get a 404 with theme and content reviewers.

**Comment by chrstinalin** [comment]
> going over abuse reports/appeals, if zip or txt files can be attached to any reviewer action, this is applied for approve/ignore actions from Resolve Reports. These would be attachments to be viewed only by reviewers (they don't go as links to any email, as it would be for a Comment).

>an author appeal could be resolved in rev tools with Deny action. The email sent has "An attachment was provided. To respond or view the file, visit https://addons.allizom.org/developers/addon/test_for_email_checks/versions." ( applied on version 4.0 in this case) but this is not an action visible for a developer in dev hub.

I took a closer look and from what I can tell, log visibility to the developer is based on the activity log's action as a constant only determined after the reviewer action is taken. It may be better to simply prevent the developer from being notified an attachment was included on an action they can't see in DevHub rather than remove the opportunity to attach files entirely (which better aligns with Andreas' input anyway)? @diox

**Comment by wagnerand** [comment]
> going over abuse reports/appeals, if zip or txt files can be attached to any reviewer action, this is applied for approve/ignore actions from Resolve Reports. These would be attachments to be viewed only by reviewers (they don't go as links to any email, as it would be for a Comment).

We can disable attaching zip/txt for these actions.

> an author appeal could be resolved in rev tools with Deny action. The email sent has "An attachment was provided. To respond or view the file, visit [addons.allizom.org/developers/addon/test_for_email_checks/versions](https://addons.allizom.org/developers/addon/test_for_email_checks/versions)." ( applied on version 4.0 in this case) but this is not an action visible for a developer in dev hub.

So, resolving an appeal from an add-on author does not show up in the devhub, but only triggers an email? Is that expected @abyrne-moz?
Does that email include reviewer comments? If not, we can disable attachments here as well. If so, let's re-discuss the expected communication.

**Comment by ioanarusiczki** [comment]
About the Deny:

a reviewer can leave a comment

![unu](https://github.com/user-attachments/assets/a5c4552b-8897-48de-9e14-a2d04709ae2d)

the email shows the comment

![2](https://github.com/user-attachments/assets/dcadd95f-005d-4b83-a152-640a1e8cb107)

>We can disable attaching zip/txt for these actions.

I'm going to file this
