### ISSUE TITLE
[Task]: Make up is, like, better

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#15066]
### Description

This Ticket encapsulates a potential solution to the issues documented in these tickets:
- https://github.com/mozilla/addons/issues/15058
- https://github.com/mozilla/addons/issues/15046
- https://github.com/mozilla/addons/issues/15034
- https://github.com/mozilla/addons/issues/15028

The solution entails:
- remove DOCKER_TARGET variable, instead relying on the DOCKER_VERSION to determine which target. Currently there are weird edge cases exposed that cannot be exposed. if DOCKER_VERSSION is "local" target is "development" otherwise it is production.
- remove the development stage. We should run the development build off the "base" stage, which should include all critical files and dependencies required for either development or production builds.
- ensure the base stage includes the necessary files (currently missing i18n files for example)
- re-organize stages after build to target production only and be as cache efficient as possible
- Use a single volume to mount "deps" which will now include static assets, generated files, and dependency directories. This dir can be mounted locally and cached in CI to ensure fast up time.
- make up should run minimum required commands to ensure container is in runnable state (e.g update_assets,deps etc) these should be heavily cached and not take much time on either dev or production build. It should also be target aware. If we are in a produciton build, the files are already in the image so we need to extract them, if a local build, we need to actually generate them.

Down sides of this approach are mostly in the last point. We are essentially moving logic out of the docker build and into makeup, which could be faster, but is more complicated and means we need to be aware of the stage we are running to know what to do.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] make up brings all containers up and running stably and consistently
- [x] make up takes less than one minute consistently
- [x] make up can run in CI with minimal work
- [x] switching between branches does not significantly impact make up time
- [ ] https://github.com/mozilla/addons/issues/15190
- [ ] https://github.com/mozilla/addons/issues/15191
- [ ] https://github.com/mozilla/addons/issues/15229
- [ ] https://github.com/mozilla/addons/issues/15230
- [ ] https://github.com/mozilla/addons/issues/15234
- [ ] https://github.com/mozilla/addons/issues/15239
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1112)

**Comment by KevinMind** [comment]
I'm not necessarily suggesting that we implement exactly what is in this issue in this issue. We can move towards a target in incremental steps. But I think at this point it is worth discussing with the team the tradeoffs and what we value more.
