### ISSUE TITLE
[Task]: Add add-on created datetime as a column to the content review queue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#15077]
### Description

While #15070 is being properly defined, we'd like to make a small change to the content-review queue to help with an ongoing event.

The created datetime of an add-on should be added as a column to the content-review.
Also, both this new column and the existing last-updated column should be sortable.

We don't need to change the format of the values for either, so going with what we have (relative datetime to _now_) is fine.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] The content-review queue shows an additional column with the datetime of the add-on relative creation date.
- [ ] Both the new column and the existing last-updated column are sortable.
- [ ] Remove the "Flags" column from the content-review queue
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1131)

**Comment by diox** [comment]
Implementation note: likely means `get_content_review_queue()` needs to stop ordering by `created`, that needs to be left to the `ContentReviewTable` (which needs to be `orderable = True`, to have a `default_order_by` and and possibly some restrictions added to columns we don't want to allow sorting by)

**Comment by wagnerand** [comment]
The other columns available are:
* Add-on: does not need to be sortable
* Flags: does not need to be sortable. We might even just remove that, I don't think the flags we have a very relevant for content-review, but we can do that in a followup.

**Comment by alexandruschek** [comment]
Hello,

I managed to check for the content-review page the following:
- the flags column is removed from content review page
- The created and last updated column are sortable
- The creation time is present
Due to this issue, I'm not able to update the filters and see if the page and the column is are still ok:
https://github.com/mozilla/addons/issues/15158

Thank you!
