### ISSUE TITLE
[Task]: Allow Decisions (from Cinder) to be held before action is carried out

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15074]
### Description

To allow decisions made on content to have a second review we need to separate the CinderDecision instance being recorded, and the action actually carried out.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] Change the model to indicates if a decision has been carried out or not
- [x] implement criteria around not carrying out the action associated with a decision immediately
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1128)

**Comment by eviljeff** [comment]
QA:
with this patch "high profile" content shouldn't have the action applied when a decision is made in Cinder.  (e.g. in cinder if a "high profile" user has a decision made which should ban them, it doesn't happen - the user isn't set to banned; their add-ons are not disabled.)  There should be a record in activity log on AMO that the attempt was made, but the action/decision was held for further consideration.  In the case of an add-on, the activity log should be exposed in the reviewer tools (and in django admin at least, for all types of content)

The criteria is in https://docs.google.com/document/d/1kOPhRdTuodEjjQSyLr1EB12bFQCCpp8SKtFR4wUXoIk/edit#heading=h.u265wpso4gc3 - it's been implemented for all content types.  Any decisions on content that does not meet the criteria should proceed as usual.

Note: the functionality to _resume_ the decision - or abandon/override it - does not exist yet.  That will be in follow-up work.

**Comment by ioanarusiczki** [comment]
I've still to check ratings and collections but I'll update for add-ons and users. 

Users:
- user with a notable addon https://addons-dev.allizom.org/en-US/firefox/user/10641606/ -> ban action held
*I used the same user and switched an addon from recommended to line or spotlight
- user with recommended add-on https://addons-dev.allizom.org/en-US/firefox/user/10643029/ -> ban action held
- user with by firefox add-on https://addons-dev.allizom.org/en-US/firefox/user/10643029/-> ban action held
- user with spotlight add-on -> https://addons-dev.allizom.org/en-US/firefox/user/10643029/ -> ban action held
- user with regular add-ons -> user is banned (expected)

Add-ons:
- recommended, by firefox, spotlight -> add-ons held for disable
- Notable -> held for disable 
*I tested the notable with 
 https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/
https://addons-dev.allizom.org/en-US/firefox/addon/notable-addon-test1/
I also tried with  https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color/ but for some reason I cannot find the reports in Cinder for this particular notable add-on and the rev tools page clearly indicated that reports have been sent. 🤷‍♀️

I read the [doc](https://docs.google.com/document/d/1kOPhRdTuodEjjQSyLr1EB12bFQCCpp8SKtFR4wUXoIk/edit#heading=h.bu7xymgvgnp8)

> Notable: Established only: The current review is not the first review since the add-on became Notable.

What I remember is that the notable on dev or stage have been taken out of the group (added to not promoted) then waited the cron task to run again to see if they're going to be flagged. It looks like with what I've been testing it's been reviewed more than once, but can't tell for sure. 🤷‍♀️

- regular add-on: add-on is disabled (expected)
- recommended theme, I tried with 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/499860
https://addons-dev.allizom.org/en-US/firefox/addon/animated-matrix-test/
but they're being disabled. Not sure, that's expected?

- no emails are sent to reporters when addons or users are held before action is carried out.

Activity logs: 

![user with notable addon](https://github.com/user-attachments/assets/595471de-045e-432a-9749-afeb287e7e69)

![addon held for disable](https://github.com/user-attachments/assets/f0fe4135-2022-4e9c-a72f-5954ff761320)

**Comment by ioanarusiczki** [comment]
Ratings and Collections look good.

Ratings:
- held for delete on recommended https://addons-dev.allizom.org/en-US/firefox/addon/webext_slug_6/
- held for delete on by firefox https://addons-dev.allizom.org/en-US/firefox/addon/webext_slug_7/reviews/
- checked a review (not a reply) on a recommended - it is deleted as before (expected)
- dev reply for spotlight add-on ->  https://addons-dev.allizom.org/en-US/firefox/addon/listed-add-on-reported/reviews/ was deleted(expected)
- dev reply for notable add-on 0-> https://addons-dev.allizom.org/en-US/firefox/addon/notable-addon-test1/reviews/ was deleted (expected)

Collections:

- Mozilla collection, multiple reports on https://addons-dev.allizom.org/en-US/firefox/collections/4757633/social_media/ -> held for delete
- another Mozilla collection https://addons-dev.allizom.org/en-US/firefox/collections/4757633/31c330a1d5594d06a7600288464732/ -> held for delete

- admin's private collection -> collection deleted (expected)
https://addons-dev.allizom.org/en-US/firefox/collections/10641574/test4/
- regular user's private collection -> collection deleted (expected)
https://addons-dev.allizom.org/en-US/firefox/collections/10642954/From-detail-page/

Other notes:
- I think Cinder's behavior looks as before, meaning that something being held is only visible on AMO's side, Cinder jobs are closed, decisions [displayed](https://stage.cinder.nonprod.webservices.mozgcp.net/queues/UXVldWVUeXBlOjMz/details/decisions?filters=%7B%7D) in their tab. 
- At these point no emails are sent (to a reporter or author) ,this should also be expected.
- Since Cinder UI changed I've noticed that I cannot go to More details inside a report, I get a Permission denied. 
- This issue is only about the Cinder side, the document mentions Partner add-ons and rev tools actions but these are future plans.
-  I remember I could ban my admin a while ago. So I made a new account and added it to admins '*' https://addons-dev.allizom.org/en-US/firefox/user/10643083/ and the ban is held. So I assume that now this applies to other mozilla users with admin permissions (such as addon reviewers, theme reviewers and so on).

**Comment by ioanarusiczki** [comment]
I tried again with themes and now force-disable action is held for: 

Recommneded https://addons-dev.allizom.org/en-US/developers/addon/alb/edit held for force disable
By Firefox theme: https://addons-dev.allizom.org/en-US/firefox/addon/a-theme-this-is-it/ is held for disable
Spotlight theme: https://addons-dev.allizom.org/en-US/firefox/addon/custom-cream_from-addons/ held for force-disable

Users: account having mozilla.com or with special permissions in admin -> I tried for admin, content reviewer, theme reviewer, admin reviewer, addon reviewer (but these are mozilla.com accounts anyway)
