### ISSUE TITLE
[Task]: Better visibility of force-enable / disable actions on add-on review page

### ISSUE THREAD

**Issue by abhn** [mozilla/addons#15099]
### Description

As an add-on reviewer, I'd like to see the add-on's force disable / enable action history in a consistent and clear way on the add-on review page ...

... in order to avoid making mis-assessments about the state in which an add-on and its versions currently are, and/or will be after I execute the force enable / disable actions.

Currently, there is inconsistency in the reviewer experience of force-enable/disable actions on the add-on review page (in terms of where the actions are logged), and a general lack of clarity for reviewers on what versions were (by a previous force enable/disable action that was later reverted), are, or will be affected by the said actions. 

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Force disabling / enabling of an add-on should be logged in `Add-on important change history` area along with the versions affected during each instance of the action and the comment associated with the action.
- [ ] https://github.com/mozilla/addons/issues/15400
- [x] When force enabling an add-on, the reviewer should have visibility into which versions will be affected by the action before committing to the action.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1153)

**Comment by abhn** [comment]
Tagging @wagnerand for feedback on the request definition!

**Comment by wagnerand** [comment]
Thanks Abhi.

I wonder you where and how see the following criterion being exposed:

```
When force enabling an add-on, the reviewer should have visibility into which versions will be affected by the action before committing to the action.
```

This might be helpful for Engineering to understand how to implement it.

**Comment by abhn** [comment]
When I wrote that I intended for it to be within the tab for force-enable action, along with the help text and comment area. 

So instead of / along with `This will force enable this add-on, and any versions previously disabled with Force Disable.`, it would be a list of versions that were previously disabled with force disable action.

For reviewer quality of life improvement, the versions could be hyperlinked the way we do for "Top 10 Version ADU" list.

**Comment by diox** [comment]
> it would be a list of versions that were previously disabled with force disable action.

The list should be cut (maybe only show the last 10 or so) to avoid showing a huge list.

**Comment by diox** [comment]
Note: adding the activity log to each version should probably be done async to avoid taking too much time if there are too many versions.

**Comment by KevinMind** [comment]
Whoever eventually works on this will have to align with operations about the finer details of the UX but in general we have a good idea how to implement this.

**Comment by diox** [comment]
@abhn could you create another (sub-) issue for "When force enabling an add-on, the reviewer should have visibility into which versions will be affected by the action before committing to the action." which we would set as P2 priority, and then we'll be able to potentially downgrade priority on that one

**Comment by abhn** [comment]
I've marked the sub-task in this issue as done and created a separate task for the said ask here: https://github.com/mozilla/addons/issues/15388

Not sure if I can mark it as a sub-issue of this? Please do so if you can.

**Comment by wagnerand** [comment]
I moved

```
Force disabling / enabling of add-ons should create a per version activity log for all the versions affected by the respective actions along with the comment associated with the action.
```

into a separate issue as well to reduce the complexity of this issue, and we might not need that eventually, as it adds further clutter to the reviewer history.

**Comment by diox** [comment]
Might be easier after https://github.com/mozilla/addons/issues/15388 is done so it's probably best to start with that one

**Comment by diox** [comment]
(this missed the 2025.04.17 tag, going to let it ride the next one because it contains quite big changes)

**Comment by diox** [comment]
Note: this won't apply to past force enable/disable actions, only new ones moving forward.

**Comment by ioanarusiczki** [comment]
Force disable/ force enable actions are both displayed in important changes history and add-on versions history. 

Some examples:
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/637319
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/637318
or with block https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/637320

I see comments from Cinder for cases when they're disabled/enabled based on an abuse report

https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/637321

Affected versions are displayed with a drop down. 
Activity logs don't have that yet, I saw there's a followup for that.
