### ISSUE TITLE
[Task]: Add Slack integration for Sentry

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#15139]
### Description

We should get notified quickly when there are new or spiking errors raised in production. Slack is made for this. Sentry supports slack notifications to public channels out of the box https://docs.sentry.io/organization/integrations/notification-incidents/slack/#rate-limiting-error.

Let's make it happen.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] A slack message is sent with anonymized content to #remora channel when there is a new issue or a spiking issue
- [ ] Find out what teams are using sentry for slack. how similar are they to AMO in terms of data
- [ ] What does legal say about the risk of leaking PII in a mozilla slack channel
- [ ] IS it possible to post sentry to private channels
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1194)

**Comment by KevinMind** [comment]
From @diox 

> We have our own scrubbing because Sentry's was not adequate (it was impossible to distinguish between an empty variable and a variable being scrubbed). But that is likely irrelevant here: it was a rare case where the IP was not in a variable/argument, but in the raw string of the exception itself. We could apply a regexp to filter that further, but there are a lot of cases where it would be too aggressive. For instance, an add-on guid can look just like an email... or in the case of IPv6, ::1 is a valid IPv6...

**Comment by diox** [comment]
For now, we should only do this if we can publish to the private channel.
