### ISSUE TITLE
[Task]: Migrate addons docs to github pages

### ISSUE THREAD

**Issue by KevinMind** [mozilla/addons#15142]
### Description

We should do one of the following:

1) migrate the doc site for this repo to github pages (like in addons-server)
2) migrate the content of this doc site to addons-server so we don't have 2 sites and instead just one.

Kind of actually prefer number 2 as it doesn't seem like we gain that much from having it separate. But if we really want it, then let's go for 1 and migrate the site

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [x] build and push docs on every PR to verfiy docs are not broken
- [x] on push to main we deploy the docs to github pages
- [x] redirect the existing read the docs site to the github pages url
- [x] disable webhooks on read the docs
- [ ] remove read the docs configuration from the repo
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1197)

**Comment by KevinMind** [comment]
Current addons-server redirects.

<img width="898" alt="image" src="https://github.com/user-attachments/assets/22e17692-90e5-4706-a898-eee4ae8cf5cf">
