### ISSUE TITLE
[Task]: Remove Git Extraction Code

### ISSUE THREAD

**Issue by chrstinalin** [mozilla/addons#15150]
### Description

Following the decommission of code-manager.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Git extraction functionality is removed.
- [ ] Reviewers API to retrieve code for a version and related code is removed
- [ ] Documentation is updated
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1208)

**Comment by diox** [comment]
In terms of API, the following should be removed:
- List Versions[](https://mozilla.github.io/addons-server/topics/api/reviewers.html#list-versions)
- Browse[](https://mozilla.github.io/addons-server/topics/api/reviewers.html#browse)
- Compare[](https://mozilla.github.io/addons-server/topics/api/reviewers.html#compare)
- Drafting Comments[](https://mozilla.github.io/addons-server/topics/api/reviewers.html#drafting-comments)

For the git extraction part, everything relying on libgit/pygit2 should be removed.

**Comment by KevinMind** [comment]
Also remove "git" from `debian_packages.txt`
