### ISSUE TITLE
[Task]: Embed developer feedback survey into Dev Hub

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#15164]
### Description

We'd like to start tracking developer sentiment so that we can work on improving our developer experience for our 3rd party extension creators.  To achieve this we need to embed the survey into the developer hub as per https://mozilla-hub.atlassian.net/browse/AMOENG-1095.

We'd like to show this to extension developers who have uploaded a new add-on version in the past thirty days.  And not show it to the same developer within the next 180 days.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Show developer survey to developers who have uploaded an add-on version in the past 30 days
- [ ] Do not show developer survey to the same developer until 180 days has passed once they dismissed the banner or clicked on the survey link.
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1226)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/75830">image-20250113-071454.png</a>

**Comment by diox** [comment]
Quick pointers:
- As described in https://mozilla-hub.atlassian.net/browse/AMOENG-1095 we'll want to bypass traditional embedding options and have a link in devhub that would open the survey page hosted by Alchemer (@abyrne-moz can give access). That way we won't have to adjust our CSP for that.
- To hide the survey to users who took it, we'll need:
  - Some model recording who took what survey (re-using an alchemer identifier maybe) and when
  - Some callback when the user clicks on the link to update that record and stop showing it to them in the future 
- This all needs to be behind a waffle switch

**Comment by ioanarusiczki** [comment]
Looking at [testing](https://github.com/mozilla/addons-server/pull/23166#issue-2915035221) , it should be fine.

After dismissing or going to [survey ](https://survey.alchemer.com/s3/7953020/MV3-Developer-Sentiment-2024) the banner is no longer displayed.

New accounts - banner is shown when a first submission is made, extension or theme.
