### ISSUE TITLE
[Task]: Regularly check for completion rate of locales on AMO, warn us if some fall below a threshold

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/addons#15175]
### Description

To improve the quality and consistency of localized content by setting thresholds for which locales remain live on the AMO, based on their completion rate of translated strings.

Proposal: https://docs.google.com/document/d/1um86jUpsw--ki0-JVIc3jKt8TrR6uHlcNWIQRpt8CRY/edit?tab=t.0

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Ensure that languages with low translation completion rates are not available on AMO website (<= 40% translated).
- [ ] A way to be notified (automatically) when a locale falls below a threshold of translatedness
- [ ] We should check addons-server / addons-frontend independently. if either drops then the locale is out on both
- [ ] Send an email Alan if we fall below the threshold for a particular locale
- [ ] Certain "primary" langauges should be included regardless of their translatedness score
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1239)

**Comment by diox** [comment]
Threshold for a locale to be removed from AMO: 40% completion in either repos
Threshold for a locale to be added to AMO if not already enabled: 80% completion in both repos
Both repos should be affected either way.

**Comment by abyrne-moz** [comment]
The proposal is a query or script that can be run against the Pontoon APIs to get a list of the languages completion rates.  Depending on engineering effort, this can be run as a scheduled task and automatically create a JIRA ticket if the completion rate for a translation goes above or below the threshold.  Otherwise, PM can run the script manually at regular intervals (Quarterly) and log the tickets for the team.

**Comment by abyrne-moz** [comment]
API https://github.com/mozilla/pontoon/tree/main/pontoon/api

API Calls:

- [https://pontoon.mozilla.org/graphql?query={project(slug:"amo"){name,localizations{locale{code,name}totalStrings,approvedStrings,pretranslatedStrings,stringsWithErrors,stringsWithWarnings,missingStrings}}}](https://pontoon.mozilla.org/graphql?query={project(slug:%22amo%22){name,localizations{locale{code,name}totalStrings,approvedStrings,pretranslatedStrings,stringsWithErrors,stringsWithWarnings,missingStrings}}})
- [https://pontoon.mozilla.org/graphql?query={project(slug:"amo-frontend"){name,localizations{locale{code,name}totalStrings,approvedStrings,pretranslatedStrings,stringsWithErrors,stringsWithWarnings,missingStrings}}}](https://pontoon.mozilla.org/graphql?query={project(slug:%22amo-frontend%22){name,localizations{locale{code,name}totalStrings,approvedStrings,pretranslatedStrings,stringsWithErrors,stringsWithWarnings,missingStrings}}})

**Comment by willdurand** [comment]
Do we know if we'll retain any RTL language? It's very useful to be able to use, e.g. `fa`, to verify how the frontend looks like in RTL mode.

**Comment by diox** [comment]
> Do we know if we'll retain any RTL language? It's very useful to be able to use, e.g. `fa`, to verify how the frontend looks like in RTL mode.

With the set of rules established in the doc and current status we would at least keep `he`. IMHO we should ensure both `ar` and `he` be kept no matter what to always keep at least 2 RTL languages.

**Comment by diox** [comment]
I manually ran the command yesterday to get us started and filed https://mozilla-hub.atlassian.net/browse/SVCSE-2551 to run it on the first of every month.
