### ISSUE TITLE
[Task]: Refactor CinderJob and ContentDecision to allow consistent use between Cinder and reviewer tools

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15220]
### Description

Currently there are two independent code paths for a decision that's made to take down an add-on if it's taken via the reviewer tools, or taken via Cinder.  Mainly because the reviewer tools carries out the action first; then logs the decision with Cinder; whereas a Cinder originated decision (obviously) has already logged the the decision; then we carry out the action. 
It also allowed one workflow to be developed without considering - or regressing - the other workflow. But the duplication is a net negative in mature code, and means that implementing _new_ features means double the engineering effort.  We should bit the bullet and refactor the differences away

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] A single (set of) functions that execute desired functionality in CinderJob
- [x] A single (set of) functions that execute desired functionality in ContentDecision
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1287)

**Comment by ioanarusiczki** [comment]
I verified on AMO dev

Emails should be as expected ✅, an example

![Image](https://github.com/user-attachments/assets/ad9c6389-411a-49ae-a963-3b102d117692)

I tried:

reject a listed version ✅
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/635302

multiple reject for unlisted  ✅
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/635373

abuse report -> rejected from rev tools ✅
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/635366

abuse report with cinder ✅
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/635304

delay reject (set up for 2 days) ❎ -- in progress, waiting for delay to expire
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/635367

delay reject with an abuse report ❎ - in progress, waiting for delay to expire
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/635368

**Comment by ioanarusiczki** [comment]
> delay reject (set up for 2 days) ❎ -- in progress, waiting for delay (of 2 days) to expire
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/635367

- first email sent ✅
- second email sent with 1 day prior to rejection ✅
- final email at rejection with an appeal url attached ✅
- appeal is sent by developer ✅
- version is flagged for HR in the Manual Review Queue ✅
- resolved with unreject + approve: content is reinstated ✅
- email is sent to the developer - that previous decision was incorrect ✅

> delay reject with an abuse report ❎ - in progress, waiting for delay to expire
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-listed/635368

- all 3 emails sent to developer✅
- appeal sent by developer and version is flagged for HR ✅
- reviewer resolves the appeal (updated another issue https://github.com/mozilla/addons/issues/15285#issuecomment-2598221214) ✅
