### ISSUE TITLE
[Task]: Improve generation to generate smaller MLBF files

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons#15261]
### Description

Recently, a new MLBF was published whose size increased by almost 100 KB in comparison to the previous MLBF. This was flagged as a performance regression in https://bugzilla.mozilla.org/show_bug.cgi?id=1938506.

EDIT: The analysis below was based on the assumption that the MLBF grew due to unexpected changes in the ratio. After checking the data in production, it seems more likely that there is a bug in the generation code that results in duplicate entries, which can also skew the ratio for no good reason. See https://github.com/mozilla/addons/issues/15261#issuecomment-2584947155

After taking a closer look, it looks like there is an actionable way towards reducing the size of the MLBF data. The full analysis is in https://bugzilla.mozilla.org/show_bug.cgi?id=1938506#c5.

Summarized, to immediately reduce the size of the hard block MLBF in production, https://github.com/mozilla/addons-server/blob/0f718e347cde838085c9f8b2f5eec8fb45f125b4/src/olympia/blocklist/mlbf.py#L55-L57 can be changed as follows:

```diff
-        cascade.set_crlite_error_rates(
-            include_len=error_rates[0], exclude_len=error_rates[1]
-        )
+        # See https://bugzilla.mozilla.org/show_bug.cgi?id=1938506#c5
+        cascade.set_error_rates([0.25, 0.5])
```

To make sure that the improvement is a strict improvement (i.e. that the above change does not negatively affect other bloomfilters for different inputs), a way to do so is to run the MLBF generation logic multiple times, and picking the smallest of all sizes.

### Acceptance Criteria

```[tasklist]
### Milestones/checkpoints
- [ ] Generated `addons-mlbf.bin` should be smaller, to fix regression reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1938506
- [ ] Generated `softblocks-addons-mlbf.bin` should not increase significantly, other than what is expected due to additional data.
- [ ] https://github.com/mozilla/addons/issues/15281
```

### Checks

- [X] If I have identified that the work is specific to a repository, I have removed "repository:addons-server" or "repository:addons-frontend"

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1332)

**Comment by KevinMind** [comment]
If I understand your analysis correctly @Rob--W the root cause of this is a decrease in the ratio of hard blocked to total versions (likely caused by normal increase in versions) and is otherwise not related to changes made in the last few months to the MLBF logic.

I was trying to look at how we have changed the logic for setting the error rates and it looks like this has been consistent since at least July 2023 (probably longer) other than that we do not set error rates if either the include or exclude list is empty as this causes errors in filter generation.

Further, it seems like we could try to integrate the formula you are using to compute the new error rate into the code so we don't need to continuously update the constant. I need to read a bit deeper but I would assume if we simply hard coded this value we solve the problem now but it could resurface if the ratio of blocked to total versions changes significantly again.

Can you sense check this for me? Am I missing something obvious so far?

**Comment by Rob--W** [comment]
I received the actual inputs that were used as part of the generation ([cache.json as written by the MLBF loader](https://github.com/mozilla/addons-server/blob/ffd993045cef73fb7635e4a94ac95e1a3a9073ec/src/olympia/blocklist/mlbf.py#L105)).

From the public MLBF I extracted the hash, and combined this with the data in cache.json (include = blocked, exclude = not_blocked + soft_blocked) to generate a new MLBF.

With the 7 nov 2024 data, my generated MLBF is identical to the one in prod, with the MLBF consisting of 845025 bytes.

But with the 17 dec 2024 data, my generated MLBF has 847859 bytes (which looks very reasonable and is what I expect), but the actual MLBF has 931343 bytes.

I think that there may be a bug somewhere in [src/olympia/blocklist/mlbf.py](https://github.com/mozilla/addons-server/blob/ffd993045cef73fb7635e4a94ac95e1a3a9073ec/src/olympia/blocklist/mlbf.py) that causes the `exclude` list to contain duplicates. Since the MLBF size is directly dependent on the sizes of `include` and `exclude` (which are `list`, not `set`), duplicate entries can result in MLBF sizes that are larger than they should be. In the mlbf.py code, I see suspicious code that suggests that there are indeed duplicates under some circumstances:
https://github.com/mozilla/addons-server/blob/ffd993045cef73fb7635e4a94ac95e1a3a9073ec/src/olympia/blocklist/mlbf.py#L186-L189

As a work-around to this bug, I think that we could de-duplicate the `include` and `exclude` inputs to [the `generate_mlbf` function](https://github.com/mozilla/addons-server/blob/ffd993045cef73fb7635e4a94ac95e1a3a9073ec/src/olympia/blocklist/mlbf.py#L41). That can resolve the immediate regression. The proper fix is to prevent duplicates from appearing in the inputs in the first place.

**Comment by KevinMind** [comment]
Fixed by https://github.com/mozilla/addons-server/pull/22983
