### ISSUE TITLE
Switch to Node 18 across all our repos

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1536]
Let's make sure we're using Node 18 everywhere as Node 16 is EOL.

- [x] https://github.com/mozilla/addons-frontend/issues/12529
- [x] https://github.com/mozilla/addons-server/issues/21393 (used for building, but also to run addons-linter)
- [x] https://github.com/mozilla/addons-customs-scanner/issues/1808
- [ ] https://github.com/mozilla/addons-code-manager/issues/2642 (just used for building and serving basic HTML - might need to be skipped, the project itself is hopefully going to be EOL soon)
- [x] https://github.com/mozilla/addons-blog/issues/603 (just used for building)
- [x] https://github.com/mozilla/extension-workshop/issues/1732 (just used for building)

Once we've migrated all environments, we should also stop testing with Node 16, using Node 18 as the base version instead, and start testing with Node 20 as the "next" version.

**Comment by diox** [comment]
Skipping code-manager as it's going away.
