### ISSUE TITLE
Expand ACR to contain e10s information

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons#163]
We have a reporter that sends information from Firefox to the developer. But it doesn't contain any e10s information about Firefox or the add-on. We can maybe improve that.

https://github.com/mozilla/ACR/
https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/

A developer can see the output in AMO and all add-ons now go through AMO when they get signed.

This is probably going to become a tracking bug.

- [x] Add in e10s status of Firefox (https://github.com/mozilla/addon-compatibility-reporter/issues/25)
- [x] Add in e10s status of add-on (https://github.com/mozilla/addon-compatibility-reporter/issues/26)
- [x] Expand ACR endpoint to accept e10s statuses (https://github.com/mozilla/addons-server/issues/3122)
- [x] Show e10s status in reports to the developer (https://github.com/mozilla/addons-server/issues/3123)
- [x] Add a badge to ACR showing e10s status (https://github.com/mozilla/addon-compatibility-reporter/issues/27)
- [x] Expose add-on e10s status in add-ons manager (https://github.com/mozilla/addon-compatibility-reporter/issues/28)
