### ISSUE TITLE
Create v5 API, freeze v4, deprecate v3

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1805]
We want to do an API version bump. The idea is to:

* [x] Rename v4dev to v5. v5 will become the new "experimental / in progress" API version mozilla/addons-server#11328
  *  [x] Move addons-code-manager to v5 instead of v4dev mozilla/addons-code-manager#675
* [x] Freeze v4 API mozilla/addons-server#16300
* [ ] Deprecate v3 API mozilla/addons-server#18759
  * [x] Make sure FxA uses v4 endpoint mozilla/addons-server#10487
  * [x] Move Firefox to v4 endpoints https://bugzilla.mozilla.org/show_bug.cgi?id=1686187
  * [x] Upgrade webext to use v4 mozilla/web-ext#2120
  * [x] notify releng to update their langpack submission script mozilla-releng/scriptworker-scripts#316

In addition, the following needs to happen but does not block _right now_ (will come back to bite us if we don't act on it though):

* [x] Move addons-frontend to use v5. Blocked by https://github.com/mozilla/addons-frontend/issues/6422 essentially.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDSRV-11)
