### ISSUE TITLE
Remove some usage of memcache

### ISSUE THREAD

**Issue by diox** [mozilla/addons#1850]
As of today, here is the full usage of memcached in addons-server:

* `amo/celery.py`: cache start time for each task in order to compute total task time when it ends. Not ideal implementation, but useful. **Keep**
* [x] `amo/utils.py`: a cache namespacing utility, that uses an intermediary cache key to be able to clear an entire key space (e.g. be able to clear all cache keys for a specific feature). Only used in reviewer tools score cache, so once that goes we could remove it entirely.
* [x] `lib/cache.py`: `memoize` and friends, to be removed, see https://github.com/mozilla/addons/issues/8531. **Done**
* `ratings/tasks.py`: cache all rating/total ratings aggregates for all valid add-ons for 60 hours. The query is relatively fast considering what it does, but this is ran on every rating, so caching could be useful here, even if it's marginal. **Keep**
* [ ] `devhub/tasks.py`: cache the validation task id for a given file upload, so that we don't validate the same thing twice. https://github.com/mozilla/addons/issues/14995
* [ ] `users/models.py`: cache denied names for default duration (500 seconds). https://github.com/mozilla/addons/issues/14994
* [x] `applications/views.py`: cache list of applications versions for default duration. https://github.com/mozilla/addons/issues/9006
* `reviewers/models.py` and `reviewers/views.py`:
  * cache addon id being reviewed to "lock" it for a short period. **Keep**
  * [x] cache a bunch of reviewer score related things (user score, recent points awarded, breakdown for a user, breakdown for a user since a certain date, leaderboard). https://github.com/mozilla/addons/issues/8522 should remove that.
* all throttling code **Keep**
* [x] views cached using `@cache_page` - see https://github.com/mozilla/addons/issues/8530 which will remove them (we should rely on the CDN for that). **Done**

Investigate what is still useful and what could be removed. We have a relatively poor cache hit ratio (it fluctuates a lot between 10 to 30 %) so a lot of it is likely counter productive.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-136)

**Comment by diox** [comment]
Filed follow-ups for remaining things to do.
