### ISSUE TITLE
Remove `docs` job from CircleCI now that we have a GitHub Action for that

### ISSUE THREAD

**Issue by diox** [mozilla/addons#2009]
As part of https://github.com/mozilla/addons/issues/9487 we added a GitHub action to build docs. That means the `docs` job in CircleCI is entirely obsolete now and we should remove it.

```[tasklist]
### Tasks
- [x] remove circleCI docs job
- [x] Migrate docs github action workflow to docker container build
- [ ] Remove readthedocs configurations
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMO2-301)
