### ISSUE TITLE
Clean up the legacy API

### ISSUE THREAD

**Issue by diox** [mozilla/addons#2520]
We need to clean up the mess that is the legacy API.

That API, written using piston and custom code, is used by Firefox in about:addons and is [lightly documented](https://developer.mozilla.org/en-US/Add-ons/AMO/Add-ons_manager_API). However, that documentation is incomplete - it does not cover authentication for instance, and therefore write/delete operations. Furthermore, some of the endpoints that are documented or even [implemented in Firefox](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/AddonRepository.jsm) appear to be unused.

On top of that we have a DRF port of the API, which according to unit tests should be 100% compatible with the piston version, but it's behind a waffle that was never enabled in prod.

The plan:
- [x] mozilla/addons-server#1715 Figure out whether the parts behind auth are still used (DELETE / POST / PUT)
- [x] mozilla/addons-server#1721 Figure out if all other GET endpoints are still useful, and whether we can remove some
- [x] ~~Figure out a test plan to test that the DRF version works fine and execute it~~
- [x] mozilla/addons-server#1729 Remove the endpoints we don't need as well as the DRF code
- [x] mozilla/addons-server#1728 Remove piston database tables
- [x] mozilla/addons-server#1737 Find a way to isolate the legacy API in the code
