### ISSUE TITLE
Review tools meta

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#282]
Review tools meta-issue:

- P1
- [x] https://github.com/mozilla/amo-validator/issues/488 - Recognize hybrid addons
- [x] https://github.com/mozilla/addons-linter/issues/811 - Linter doesn't warn about the use of innerHTML
- [x] https://github.com/mozilla/amo-validator/issues/461 - Validator ineffective in some cases (shows nothing)
- [x] https://github.com/mozilla/amo-validator/issues/370 - Validator is missing issues
- [x] https://github.com/mozilla/addons-linter/issues/1047 - eval() not caught
- P2
- [ ] https://github.com/mozilla/addons-server/issues/1542 - Review submitted for latest version instead of loaded version
- [x] https://github.com/mozilla/addons-server/issues/3619 - Files are not accessible after a rejection  / being fixed and investigated in https://github.com/mozilla/addons-server/issues/4649
- [x] https://github.com/mozilla/addons-server/issues/3913 -  Notify reviewers when "notes to reviewers" is updated
- P3
- [x] https://github.com/mozilla/addons-server/issues/2414 - Moderated Reviews Count wrong
- [x] https://github.com/mozilla/addons-server/issues/1137 - Blank search no longer shows admin flagged addons
- [x] https://github.com/mozilla/addons-server/issues/3782 - Add links for reviewers and admins
- [x] https://github.com/mozilla/addons-linter/issues/699 - Add retire.js
- TBD
- [x] https://github.com/mozilla/addons/issues/132 - Can't upload source code for an add-on if the filename or slug contains non-ascii chars
- [x] https://github.com/mozilla/addons-server/issues/3989 - Update editor tools to handle unlisted and listed versions
- [x] https://github.com/mozilla/addons-server/issues/4148 - File viewer marks file as deleted which wasn't actually deleted

NOTES…
 * https://github.com/mozilla/amo-validator/issues/488 - Recognize hybrid addons – can and should be extended to have addons-linter running but at this moment addons-linter isn't really helpful for validation so this is more important...

**Comment by muffinresearch** [comment]
@wagnerand to be able to address the p1 next year it would be useful if the remaning p1s could be reviewed. A lot of the P1 issues relating to lint / validator problems are links to files that devs may not be able to open. 

It help a lot if those bugs were clarified with specific examples that should be detected. Multiple examples per issue are fine or a linked file that we can get access to as long as it's clear what a successful patch should catch.

**Comment by jvillalobos** [comment]
I agree that concrete examples are necessary. As for file access, I can arrange that for anyone in the dev team who needs to test the validator/linter.

**Comment by wagnerand** [comment]
@muffinresearch I double-checked the P1s and all of them include real-world examples from production add-ons.

As @jvillalobos said, we can easily provide the files to engineers if they are not available.
