### ISSUE TITLE
Admin tools meta issue

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons#283]
Tracker for admin tools issues or issues that affect admins:

- P1
- [x] https://github.com/mozilla/addons-server/issues/3970 - Shouldn't be possible to submit new version for disabled add-ons
- P2
- [x] https://github.com/mozilla/addons-server/issues/3876 - Disabling & enabling add-on in review causes inconsistent status
- [x] ~~https://github.com/mozilla/addons-server/issues/3873 - Improve the admin tool for sending emails to developers~~
- [x] https://github.com/mozilla/addons-server/issues/3573 - Add-ons /w only disabled versions can't be "Awaiting full review"
- [x] https://github.com/mozilla/addons/issues/271 -  Deleting and Re-adding a file inside a version pending review causes incorrect add-on status
- P3
- TBD

**Comment by diox** [comment]
Obsolete tracker bug, closing.
