### ISSUE TITLE
Remove FxA migration and unused password code

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons#3271]
Once we have flipped the migration waffle off we can remove a lot of code.

Remove the migration waffle since we're never going back.

Drop the password column if possible and update anything that is expecting a password (`make initialize_docker` and change password, for example). If the password column cannot be dropped it should at least be set to unusable passwords and support for setting passwords on users should be removed.
- [x] Remove migration waffle.
- [x] Remove login view.
- [x] Remove change password code.
- [x] Remove forgot password code.
- [x] Remove blacklisted password.
- [x] Remove blacklisted email code.
- [x] Remove change email code.
- [x] Remove user registration, confirmation and all code dealing with `confirmationcode`.
- [x] Remove password from "super-create" user API.
- [x] Update `./manage.py createsuperuser`.
- [x] Update `self.client.login()` calls.
- [x] Remove password code from model and tests and any settings (like `PASSWORD_HASHERS`).
- [x] Remove `fxa-migrated` waffle and `user.fxa_migrated()`.
- [x] Remove fxa mail in zadmin forms/views.
- [x] ~~Remove password and confirmationcode column/data~~ (#3746).
- [ ] ~~Move some accounts code into an authentication backend~~ (#3799).
- [x] ~~Update documentation about 3rd party AMO support~~ (#3867).
- [x] Any unused JS
