### ISSUE TITLE
[tracker] Switch to django-migrations

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons#3600]
This is the overall tracking issue to manage progress on switching to Django's builtin migrations framework.

We are currently using https://github.com/mozilla/schematic/ which is a very simplified migrations script which leads to writing plain SQL migrations and having a hard time with data migrations and lots of one-off scripts.

(copied from https://github.com/mozilla/addons/issues/3600)
* [x] Make sure the dev, stage and prod database schema are mostly identical (#10916)
* [x] Then make sure we are able to generate a schema locally that looks like -dev, or go the other way around and implement a migration that migrates -dev, -stage and -prod to something like -local. I haven't looked too deep into this so I can't really say which may be more complicated (#10917) 
* [x] Then switch to django-migrations :) (#12333)
  * Add initial migrations
* [x] Remove old migrations files  (#12390)
