### ISSUE TITLE
Fix/Replace/Upgrade Python3 dependencies

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#4177]
https://pyup.io/account/repos/github/mozilla/addons-server/
Old dependencies that aren't compatible are blocking our smooth and totally uncomplicated upgrade of addons-server codebase to Python3, so we need to fix those first.

Work needed for prod / local development:
* [x] schematic ==0.4 - mozilla/schematic#4 (but obsolete after django migrations mozilla/addons#3600 anyway)

Obsolete so will be removed:
* [x] amo-validator ==1.10.55 mozilla/addons-server#10502
  * [x] fastchardet ==0.2.0
  * [x] spidermonkey ==54.0a2.post2 mozilla/python-spidermonkey/pull/9

False positives:
* [x] filelock ==3.0.10 - travis.yml indicates it is py3 compatible.
* [x] futures ==3.2.0 - just a backport of py3 functionality to py2
* [x] pathtools ==0.1.2 - pretty unmaintained but is seemingly only used by Celery, which _is_ py3 compatible so safe to ignore.
* [x] hawkauthlib ==2.0.0  - repo pull requests and tox.ini indicate it is py3 compatible.
* [x] PyFxA ==0.5.0  - repo pull requests and travis.yml indicate it is py3 compatible.

Finished, changes merged into addon-server:
* [x] ~atomicwrites ==1.1.5~
* [x] ~basket-client ==0.3.12 - _might_ be so simple it's py3 compatible anyway.~
* [x] ~django-cache-nuggets ==0.1.1 mozilla/addons-server#4998~
* [x] ~django-cronjobs ==0.2.3 mozilla/addons-server#5050~
* [x] ~django-mobility (https://github.com/jbalogh/django-mobility) - only used for mobile pages mozilla/addons-server#5055~
* [x] ~django-quieter-formset ==0.4 mozilla/addons-server#5005~
* [x] ~django-multidb-router ==0.6 https://github.com/jbalogh/django-multidb-router/pull/31~
* [x] ~django-statsd-mozilla ==0.3.16 https://github.com/django-statsd/django-statsd/pull/98~
* [x] ~flake8-mutable ==1.1.0 https://github.com/ebeweber/flake8-mutable/pull/10~
* ~flufl.lock 2.4.1 - only supports python 2 and version 3.2 only supports python 3. Separate py3 requirements file added.~
* [x] ~fxapom ==1.10.0 https://github.com/mozilla/fxapom/issues/97~
* [x] ~jingo-minify ==0.6.0 folded into addons-server~
* [x] ~moz-addon-packager ==1.0.1 mozilla/addons-server#5012~
* [x] ~MySQL-python ==1.2.5 mozilla/addons-server#5002~
* [x] ~M2Crypto ==0.24.0 https://github.com/mozilla/addons-server/pull/5801~
  * [x] ~django-aesfield ==0.3.0 https://github.com/andymckay/django-aesfield/pull/10~
  * [x] ~m2secret ==0.1.1 replaced with https://pypi.python.org/pypi/m2secret-py3~
  * [x] ~signing-clients ==0.1.14 https://github.com/mozilla/signing-clients/pull/19~
* [x] ~mozilla-logger ==0.2 - Got removed once we switched completely to Logging 2.0 (See mozilla/addons#4149)~
* [x] ~sphinxcontrib-httpdomain ==1.5.0~
* [x] ~ supervisor ==3.3.4 - master branch is py3 compatible so switched to that as it's only used in local development. mozilla/addons-server#10339 ~
