### ISSUE TITLE
Implement Add-ons Post-Review Process

### ISSUE THREAD

**Issue by diox** [mozilla/addons#4271]
This is a tracking bug for implementing Add-ons post-review process.

Essentially post-review is the follow-up of https://github.com/mozilla/addons/issues/3964 : the goal is to automatically approve WebExtensions without human intervention ; human reviews are done after the add-on has been pushed to public, prioritized depending on various factors.

* PRD: https://docs.google.com/document/d/1hVx-NbuVRc0wKXSdt8eHceObexY93YFzMXtqYC95nUs/edit
* Implementation plan with what we care about for Q2: https://docs.google.com/document/d/1rZvM2QGk8WtkNUDRvLEvrbqZ190hvHfOle4zVRllQmw/edit
* Post-review weights for prioritization https://docs.google.com/spreadsheets/d/1CZEECHHqEmK87fNiWNslAsFQBL7zxYF-c63-zZVZuqw/edit#gid=0

Steps:
1. [x] Deploy current auto-approval implementation (which auto-approves a fraction of WebExtensions *updates* that match some criteria) mozilla/addons#4248, mozilla/addons#3964
2. [x] Implement list of auto-approved add-ons in reviewer tools mozilla/addons#4247
3. [x] Allow human reviewers to confirm approval of automatically approved add-ons (or reject them), tweak reviewer tools to display abuse reports etc more prominently. mozilla/addons-server#5258
4. [x] Post-review list prioritization with risk factors evaluation. mozilla/addons-server#5473 
5. [x] Add static flags analysis to the risk factors used for prioritization. mozilla/addons-server#5475
6. [x] Submission process updates. mozilla/addons-server#5579
7. [x] Remove auto-approval restrictions, making all WebExtensions that pass validation auto-approved automatically. mozilla/addons-server#5665
