### ISSUE TITLE
use npm for our libs

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#4370]
Security! Prosperity! 

Contents of /lib/ that we need to migrate to using npm:

- [x] jqModal.js  mozilla/addons-server#5702
- [x] jquery-ui mozilla/addons-server#5580 
  - jquery-ui\autocomplete.js
  - jquery-ui\core.js
  - jquery-ui\datepicker.js
  - jquery-ui\menu.js
  - jquery-ui\mouse.js
  - jquery-ui\position.js
  - jquery-ui\sortable.js
  - jquery-ui\widget.js
- [x] jquery-1.12.0.js mozilla/addons-server#5571
- [x] jquery.browser.js mozilla/addons-server#5585
- [x] jquery.cookie.js mozilla/addons-server#5585
- [x] jquery.minicolors.js  mozilla/addons-server#5713
- [x] jquery.pjax.js ~#5585~ reverted in mozilla/addons-server#5678 now mozilla/addons-server#5717
- [x] jquery.timeago.js mozilla/addons-server#5585
- [x] less.js mozilla/addons-server#5586
- [x] raven.min.js  ~#5698~ mozilla/addons-server#5705
- [x] underscore.js mozilla/addons-server#5659
_Consciously skipping_
- [ ] syntaxhighlighter  (https://www.npmjs.com/package/syntaxhighlighter; would be a major update)
  - syntaxhighlighter\shBrushCss.js
  - syntaxhighlighter\shBrushJava.js
  - syntaxhighlighter\shBrushJScript.js
  - syntaxhighlighter\shBrushPlain.js
  - syntaxhighlighter\shBrushXml.js
  - syntaxhighlighter\shCore.js
  - syntaxhighlighter\shLegacy.js
- [ ] highcharts.src.js   (https://www.npmjs.com/package/highcharts; huge package and may be a significant update)
_Deleted_
- [x] ~amd.js mozilla/addons-server#5572~
- [x] ~csrf.js mozilla/addons-server#5572~
- [x] ~flipsnap.js mozilla/addons-server#5572~
- [x] ~jqmobile.js mozilla/addons-server#5572~
- [x] ~moment-with-langs.min.js mozilla/addons-server#5572~
- [x] ~uri.js mozilla/addons-server#5572~
_Not on NPM_
- [x] diff_match_patch_uncompressed.js
- [x] format.js
- [x] jquery.hoverIntent.js
- [x] jquery.zoomBox.js
- [x] ngettext-overload.js (is unneeded in Django 1.10+ too)
- [x] popcorn-1.0.js
- [x] truncate.js
- [x] ui.lightbox.js (original host and project page is gone)
