### ISSUE TITLE
Simplify Contributions feature

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#4615]
This is a tracking issue for the changes to the Contributions feature, as specified in [this document](https://docs.google.com/document/d/1DjXQbl_hZlRe4bqE9B-cLPfq64wYFa19TU9DfsOpckQ/edit?ts=597f51b1#).

- [x] [Product] Ask developers for domains they would like to use for contributions.
- [x] Add a Contributions URL field in the developer tools. mozilla/addons-server#6070
- [x] [Product] Notify developers so they can fill in the new field.
- [x] Change Contribute section in listing pages (old front-end). mozilla/addons-server#6071
- [x] Change data sent in Add-ons Manager (legacy) API. mozilla/addons-server#6308
- [x] Expose Contributions URL in Addon (v3) API. mozilla/addons-server#6434
- [x] Remove Developer Profile and Roadblock pages. mozilla/addons-server#6072
- [x] Remove Manage Developer Profile and Manage Payments sections in devhub. mozilla/addons-server#6073
- [x] Remove Contributions section from developer statistics dashboard. mozilla/addons-server#6074
- [x] Additional cleanup (Paypal code, unused DB fields). mozilla/addons-server#6076
- [x] Implement UI on new frontend (https://github.com/mozilla/addons-frontend/issues/3149)

This opening comment will be updated as the plan evolves.
