### ISSUE TITLE
Support WebExtensions language packs

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#4722]
@zbraniecki and team are working on an implementation of language packs using a WebExtensions package. [Bug 1395363](https://bugzilla.mozilla.org/show_bug.cgi?id=1395363) is tracking their deployment, and AMO support is one of the blockers.

There are a few things we need to do:

* [x] Detect if the XPI is a language pack and give it the correct type, since it's not an extension. mozilla/addons-server#6350.
* [x] In the linter, validate that the add-on _only_ includes the language pack manifest flags. Language packs shouldn't run any code. mozilla/addons-linter#1526.
* [x] We'll probably need to _require_ the use of `strict_min_version` and `strict_max_version`, since legacy language packs have implicit strict compatibility. Also mozilla/addons-linter#1526.
* [x] Look into the legacy validator for any other checks we perform specifically on language packs (I don't remember any), and determine if they should be ported to the linter. Also https://github.com/mozilla/addons-linter/issues/1526.
* [x] Update the language pack import tool (if needed) to support these new packages. mozilla/addons-server#6360
