### ISSUE TITLE
[Tracker] Updating Reviewer Recognition Program 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons#4793]
This is a tracking issue for changes to the reviewer recognition program as specified in [this document](https://docs.google.com/document/d/1O-dOi_PafpOpZ7SWPpKUK7qs5ARkS0CMCP5xpJfDrDE/edit#). 

**Queue Modifications**
- [x] Do not expose extensions in lowest risk factor range  -- issue mozilla/addons-server#6472 
[_Note: range to be determined once feature is turned on in prod_]

**Points System Modifications**
- [ ] Add new reviewer behaviors and assign points -- Issue mozilla/addons-server#6473
_Note: point values subject to change_

**Reporting**
- [ ] Set up automated quarterly reporting with reviewer's ID, reviewer's name, number of add-ons reviewed that quarter, and number of points achieved that quarter. Report can come as a .csv or .xls file, or be dropped into a Google sheet. -- Issue mozilla/addons-server#6474

**To Be Determined**
- [x] Associating add-on risk factor ranges with reviewer behaviors
