### ISSUE TITLE
Reviewer tools work for Q4

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#4829]
This is tracking bug for the reviewer tools work planned for Q4.
- [ ] Send quarterly report for reviewer activity. mozilla/addons#4803
- [x] Color weights in auto-approved queue. mozilla/addons-server#6518
- [x] Unified reviewer dashboard. mozilla/addons-server#6522
