### ISSUE TITLE
[Tracker] Support Static Themes on AMO

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#501]
Tracker for all the issues needed to fully support Static Themes (aka New Themes, aka Webextension Themes) on AMO.  Static themes have no JS code. Extensions that use the Theme API (dynamic themes) are treated as normal extensions and are out of scope for this work.

[PRD](https://docs.google.com/document/d/1d9acBumpdK87sYg7Ah98BEKvL7b4tuO-RDpgqbm7FTs/edit#)
[Migration cases](https://docs.google.com/document/d/18Wyc7l7Na2pVtaU1j4VhCM63nbawziOzIFJC_giRk74/edit#)
Model discussion mozilla/addons-server#6574
Preview problems brain-dump mozilla/addons#568

* [x] Enable submission of packaged Static Theme
  * [x] Submission via devhub submit Add-on [mozilla/addons-server/issues/6572]
  * [x] Validate Static Theme [mozilla/addons-linter/issues/1587]
  * [x] ~Submission via API (no special support added, but can be submitted exactly as Extensions can - with the same limitations about listed/unlisted versions)~
  * [x] Create new submission wizard for Static Themes (a-la the existing LWT/Persona wizard) [mozilla/addons-server#6860]
    * [x] wizard for new versions too [mozilla/addons-server#7018]
    * [x] support additional backgrounds [mozilla/addons-server#7019]
  * [x] Generate preview(s) of static theme from submission [mozilla/addons-server#7056]
* [x] Handle Static Theme correctly in devhub [mozilla/addons-server#6764]
* [x] Handle Static Theme correctly in reviewer tools. [mozilla/addons-server#7385]
* [x] Allow installation of Static Theme
  * [x] Serve extra properties in the API to allow preview, etc. [mozilla/addons-server#6804]
  * [ ] Handle category/detail/install in frontend [mozilla/addons-frontend#3388]

**Comment by eviljeff** [comment]
Assigning to @jvillalobos to correct and file appropriate follow-ups - the many different PRDs written over the last year are hard to distill down into exactly what needs to be done.

**Comment by jvillalobos** [comment]
Made some edits to the opening comment. We're not doing anything extra for dynamic themes (AFAICT), so this should be focused on supporting static themes. Also, the PRD link was pointing to a migration cases doc that doesn't cover most of the spec.

**Comment by jvillalobos** [comment]
All future tracking should happen on https://github.com/mozilla/addons-frontend/projects/6
