### ISSUE TITLE
Remove beta version support

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#5116]
- [x] Email developers using beta versions, explaining that this feature will be removed soon and alternatives to use (PM).
- [x] Disable beta version submission and listing, gated by a waffle switch. (#7435)
- [x] Publish blog post explaining removal and update documentation (PM).
- [x] Redirect beta update pings to the main branch. (#7830)
- [x] Flip waffle switch (PM).
- [x] Disable all files with beta status. (#7904)
- [x] Remove code related to beta versions. (#8099)
- [x] Remove `beta-versions` waffle flag. (#8660)
