### ISSUE TITLE
Review process updates

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#5120]
This is a tracker for the changes to be done to the existing reviewer tools, as specified in the [Reviewer Tools PRD](https://docs.google.com/document/d/1Me-2Qx-C7cMptKQt_-1gAyPZCBOiww9laQLEMlD9N2M/edit). These changes will be done in the existing tools because the UX and architectural redesign work is a longer term project that will be tackled in phases, and these changes are a more immediate need.

- [x] Create a `Reviewers: Admin` group with `Reviews:Edit` permission. mozilla/addons-server#7279
- [x] Add a `Reviewer Tools` item to the user dropdown on AMO, pointing to the dashboard. mozilla/addons-server#7280
- [x] Create "More Actions" section in review pages mozilla/addons-server#7282
  * Add toggle to be notified about all future listed updates.
  * Unflagging for admin review.
  * Disable listing.
- [x] Add a deadline for requests for information. mozilla/addons-server#7283
- [x] Disable auto-approval of future listed versions. mozilla/addons-server#7284
