### ISSUE TITLE
AMO Admin Tools, phase 1

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#5122]
This is a tracker for the implementation of the first phase of the AMO Admin Tools, as specified in the [Admin Tools PRD](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit). This first phase focuses on setting up the basic framework (permission groups, index) and the tools required for homepage curation and spam mitigation.

- [ ] Give the `System Administrators` group a new `All:Admin` permission that will gate all admin features specified in the PRD as Full admin tools. mozilla/addons-server#7249
- [x] Create a `Curators` group with a new `Content:Curate` permission that will gate all features specified in the PRD as Content curator tools. mozilla/addons-server#7250
- [x] Add an `Admin Tools` item to the user dropdown on AMO, pointing to an index of available admin tools. mozilla/addons-server#7251
- [ ] [Blocked text content](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.hs3rkqx0bfty). mozilla/addons-server#7252
- [x] [User admin](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.b7y5z7x7pzhe): show all content for user, banning, deleting. mozilla/addons-server#7268
- [x] [Replacement add-ons](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.3wbd4ya878ev). mozilla/addons-server#7253
- [ ] [Homepage content curation](https://docs.google.com/document/d/1ts_1IB3hXcTvEX0gclN55NsBVs7r1duBOM9zQaqSyhE/edit#heading=h.wi0zo8c4banm). mozilla/addons-server#7261
