### ISSUE TITLE
Support bigger screenshot uploads

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons#5384]
This is a tracker for a Q2 project for improving add-on screenshot sizes. These are the tasks that need to be covered:

- [x] Allow uploading larger images on devhub mozilla/addons-server#7908.
- [x] Document maximum and recommended image sizes on devhub mozilla/addons-server#7909.
- [x] Stop upscaling images on front-end mozilla/addons-frontend#4197.
- [x] Show thumbnails for screenshots mozilla/addons-frontend#5338
- [ ] Ensure front-end shows the right dimensions for the image https://github.com/mozilla/addons-frontend/issues/1519. 
- [x] [PM] Communicate changes to add-on devs and update featuring guidelines.
