### ISSUE TITLE
Remaining legacy migration problems before django migrations

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#6974]
Prod has the following problems that need addressing

- [x] some `FileValidation` don't have a valid fk to a `File` mozilla/addons-server#12393
- [x] some `UpdateCount` don't have a valid fk to an `Addon` https://github.com/mozilla/addons-server/pull/12406
- [x] more than one `License` is linking to the same `Translation` mozilla/addons-server#12392
- [x] migrations were stopped at 1197 and the remaining migrations (1197 to 1212 inclusive) we skipped.  They _may_ have other errors in them when executed for the first time on prod db.  [#12405]

In addition, we found this issue on stage and will affect prod too
- [x] changing to the default collation on username charfield is prevented by case-insensitive duplicates mozilla/addons#1812
