### ISSUE TITLE
remove/reimplement all non-django-admin views under /admin

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#7131]
our current admin dashboard in /admin is bundle of ancient tools that do certain adminy things; plus there's a link to the django model admin. Lets drop all of the ancient tooling and if we do need that functionality still, reimplement it in django admin views.

Tools:
* [x] addon search mozilla/addons-server#15292
* [x] user search mozilla/addons-server#15292
* [x] addon manage mozilla/addons#5555, mozilla/addons-server#15234
* [x] Featured add-ons  (should be obsolete, but featured add-on support is still in the codebase)
* [x] Fake mail mozilla/addons-server#12994
* [x] view site settings mozilla/addons-server#15232
* [x] view request environment mozilla/addons-server#15232
* [x] manage elasticsearch mozilla/addons-server#15232
* [x] hidden/unlinked views mozilla/addons-server#15296
  * fix-disabled
  * download upload file
* [x] landing page mozilla/addons-server#15310

(excluding links in the header to tools already implemented in django admin views, like Replacement Add-ons)
