### ISSUE TITLE
django3.2 blockers

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#8193]
mozilla/addons#8166 dealt with some problems identified from reading release notes, and getting the majority of the tests running in CI.  This issue will track the remaining blockers

* [x] django3.2 is actually released 😄 
* [x] failing tests in the ES job caused by faulty teardown in `TestIndexCommand` mozilla/addons-server#16492
* [x] settings.LANGUAGES needs to be a list of tuples mozilla/addons#8188
* [x] change constraint&index names to be unique across models (or bypass check) mozilla/addons-server#16497
* [x] enable django3.2 on addons-dev mozilla/addons-server#17449
* ? (add to as we test and investigate more)
