### ISSUE TITLE
make our codebase support django 4.1

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#8842]
We're currently running django 3.2, and as a policy stick to LTS releases of django, so the next release we'd upgrade to is django 4.2.  But it doesn't hurt to get ahead of the 4.2 alpha release and where possible make our codebase compatible with newer django.  

- [x] mozilla/addons#8510
- [x] mozilla/addons-server#19606
- [x] mozilla/addons-server#19607
- [x] mozilla/addons-server#19609
- [x] mozilla/addons-server#19610
- [x] mozilla/addons-server#19611
- [x] mozilla/addons-server#19613
- [x] mozilla/addons-server#19614
- [x] mozilla/addons-server#19639
- [x] mozilla/addons-server#19638
- [x] mozilla/addons-server#19640
- ...
