### ISSUE TITLE
Create new search page for about:addons search

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons#9784]
- [ ] Create UX for search page https://github.com/mozilla/addons/issues/9768/TBD
- [ ] Design the new mobile search page mozilla/addons#9768
- [x] Rename the search app to admin mozilla/addons#9775
- [ ] Implement a search component mozilla/addons#9748
- [ ] Implement a search results page mozilla/addons#9749
